// 世说新语 · 魏晋风流人物谱系图 —— 数据源
// 主轴：琅琊王氏 + 陈郡谢氏；辅：竹林七贤 + 名士·隐逸
//
// 坐标双轨：
//   x / y   —— 横版（landscape, viewBox 1560×1440）
//   px / py —— 竖版（portrait,  viewBox 1080×1920）
// 关系曲线控制点：bend（横版） / pbend（竖版）
// 连线颜色用语义 key（parent/sibling/cousin/couple/social/rupture），由渲染层按明暗主题解析。
window.SHISHUO = {
  meta: {
    title: "世说新语 · 魏晋风流人物谱系图",
    subtitle: "王谢两大家族为主轴 · 竹林七贤 · 名士交游",
    note: "谱系主据《晋书》《世说新语》；生卒年约数处标“约”。",
  },

  // 家族/圈层 → 颜色（两种主题通用）
  clans: {
    "竹林七贤": "#4f7a4f",
    "琅琊王氏": "#3f5f8a",
    "陈郡谢氏": "#a83a2f",
    "名士·隐逸": "#8a7a5c",
  },

  // 关系类型 → 样式（line: 实/虚，arrow: 是否箭头，color: 语义色 key）
  relTypes: {
    "父子":   { line: "solid",  arrow: true,  color: "parent" },
    "父女":   { line: "solid",  arrow: true,  color: "parent" },
    "祖孙":   { line: "solid",  arrow: true,  color: "parent" },
    "族祖孙": { line: "solid",  arrow: true,  color: "distant" },
    "兄弟":   { line: "solid",  arrow: false, color: "sibling" },
    "从兄弟": { line: "solid",  arrow: false, color: "cousin" },
    "叔侄":   { line: "solid",  arrow: false, color: "sibling" },
    "叔侄女": { line: "solid",  arrow: false, color: "sibling" },
    "夫妻":   { line: "double", arrow: false, color: "couple" },
    "交游":   { line: "dashed", arrow: false, color: "social" },
    "决裂":   { line: "dashed", arrow: false, color: "rupture" },
  },

  // people: id/name/zi/clan/years/title/bio/ep(剧集)/x/y(横)/px/py(竖)
  people: [
    // ── 竹林七贤（横版圆形 · 竖版圆形）────────────────────────
    { id: "jikang",  name: "嵇康", zi: "叔夜", clan: "竹林七贤", years: "224–262",
      title: "七贤之首 · 中散大夫", x: 260, y: 440, px: 540, py: 195,
      bio: "竹林七贤之首。美姿容、善琴，临刑前索琴弹《广陵散》，叹“《广陵散》于今绝矣”。" },
    { id: "ruanji",  name: "阮籍", zi: "嗣宗", clan: "竹林七贤", years: "210–263",
      title: "步兵校尉", x: 150, y: 493, px: 400, py: 250,
      bio: "以“青白眼”看人，驾车至穷途则恸哭而返。《世说》称其“胸中垒块，故须酒浇之”。" },
    { id: "shantao", name: "山涛", zi: "巨源", clan: "竹林七贤", years: "205–283",
      title: "吏部尚书", x: 397, y: 611, px: 695, py: 425,
      bio: "举荐嵇康出仕，反遭嵇康《与山巨源绝交书》；嵇康临终却托孤于他，为千古知己之辩。" },
    { id: "xiangxiu",name: "向秀", zi: "子期", clan: "竹林七贤", years: "约227–272",
      title: "注《庄子》者", x: 321, y: 706, px: 480, py: 525,
      bio: "与嵇康锻铁于洛邑，嵇康死后作《思旧赋》悼之，欲言又止，成千古悲调。" },
    { id: "liuling", name: "刘伶", zi: "伯伦", clan: "竹林七贤", years: "约221–300",
      title: "酒仙", x: 199, y: 706, px: 600, py: 525,
      bio: "嗜酒放达，常乘鹿车携酒，令人荷锸相随，曰“死便埋我”。《酒德颂》作者。" },
    { id: "wangrong",name: "王戎", zi: "濬冲", clan: "竹林七贤", years: "234–305",
      title: "司徒 · 琅琊王氏", x: 370, y: 493, px: 680, py: 250,
      bio: "七贤中最年少，出身琅琊王氏。以贪吝与清谈并称，“卿卿我我”典故即出其口。" },
    { id: "ruanxian",name: "阮咸", zi: "仲容", clan: "竹林七贤", years: "约234–305",
      title: "阮籍之侄 · 妙解音律", x: 123, y: 611, px: 385, py: 425,
      bio: "阮籍之侄，与叔父并称“大小阮”。善弹琵琶，乐器“阮咸”即因其得名。" },

    // ── 琅琊王氏 ───────────────────────────────────────────
    { id: "wangxiang", name: "王祥", zi: "休徵", clan: "琅琊王氏", years: "184–268",
      title: "孝圣 · 卧冰求鲤", x: 600, y: 190, px: 540, py: 640,
      bio: "“卧冰求鲤”“黄香温席”同列二十四孝，琅琊王氏由他发迹，为士族第一高门之祖。" },
    { id: "wangyan",  name: "王衍", zi: "夷甫", clan: "琅琊王氏", years: "256–311",
      title: "西晋清谈领袖", x: 600, y: 320, px: 540, py: 725,
      bio: "西晋太尉，清谈领袖，坐谈“贵无”而误国。石勒破洛阳杀之，叹“王衍清谈误国”。" },
    { id: "wangdun",  name: "王敦", zi: "处仲", clan: "琅琊王氏", years: "266–324",
      title: "大将军 · 王导从兄", x: 520, y: 450, px: 300, py: 815,
      bio: "王导从兄，与王导共扶晋元帝渡江，后起兵叛乱（王敦之乱），为王导所忌的“逆臣”。" },
    { id: "wangdao",  name: "王导", zi: "茂弘", clan: "琅琊王氏", years: "276–339",
      title: "东晋丞相 · 江左风流宰相", x: 600, y: 450, px: 460, py: 815,
      bio: "东晋开国元勋，时谚“王与马，共天下”。宽和善处，历事三朝，王氏由此为第一望族。" },
    { id: "wangkuang",name: "王旷", zi: "世弘", clan: "琅琊王氏", years: "生卒不详",
      title: "王羲之之父 · 王导从弟", x: 680, y: 450, px: 620, py: 815,
      bio: "王导从弟，王羲之之父，官淮南内史。早年劝元帝渡江，是“渡江”之议的发起者之一。" },
    { id: "wangxizhi",name: "王羲之", zi: "逸少", clan: "琅琊王氏", years: "303–361",
      title: "书圣 · 右军将军", x: 600, y: 580, px: 620, py: 905,
      bio: "“书圣”，《兰亭集序》作者。永和九年与谢安、孙绰等会于会稽兰亭，为千古风流盛事。" },
    { id: "wangxun",  name: "王珣", zi: "元琳", clan: "琅琊王氏", years: "349–400",
      title: "王导之孙 · 才子", x: 460, y: 700, px: 460, py: 905,
      bio: "王导之孙，与王羲之并称才俊。善书，今存《伯远帖》为“三希堂”之一。" },
    { id: "wangningzhi", name: "王凝之", zi: "叔平", clan: "琅琊王氏", years: "？–399",
      title: "王羲之次子 · 谢道韫之夫", x: 520, y: 700, px: 400, py: 995,
      bio: "王羲之次子，谢道韫之夫。笃信五斗米道，孙恩之乱时守会稽不设备，城破被杀。" },
    { id: "wanghuizhi", name: "王徽之", zi: "子猷", clan: "琅琊王氏", years: "约338–386",
      title: "王羲之第五子", x: 610, y: 750, px: 540, py: 995, ep: ["EP01 雪夜访戴", "EP03 看竹"],
      bio: "字子猷，王羲之第五子。雪夜访戴“乘兴而行，兴尽而返”；爱竹“何可一日无此君”。本系列主角之一。" },
    { id: "wangxianzhi", name: "王献之", zi: "子敬", clan: "琅琊王氏", years: "344–386",
      title: "王羲之第七子 · 小圣", x: 700, y: 700, px: 680, py: 995,
      bio: "王羲之第七子，书艺与父并称“二王”。“管中窥豹”即出自其少年逸事。" },

    // ── 陈郡谢氏 ───────────────────────────────────────────
    { id: "xiekun",   name: "谢鲲", zi: "幼舆", clan: "陈郡谢氏", years: "281–324",
      title: "名士 · 谢尚之父", x: 940, y: 450, px: 344, py: 1120,
      bio: "陈郡谢氏早世名士，与王敦、卫玠交游。后人追念其风度，为谢氏高门奠基者之一。" },
    { id: "xiepou",   name: "谢裒", zi: "字佚", clan: "陈郡谢氏", years: "？",
      title: "谢安之父 · 谢鲲弟", x: 1060, y: 450, px: 544, py: 1120,
      bio: "谢鲲之弟，官太常卿。生六子：谢奕、谢据、谢安、谢万、谢铁、谢石，谢氏由此鼎盛。" },
    { id: "xieshang", name: "谢尚", zi: "仁祖", clan: "陈郡谢氏", years: "308–357",
      title: "谢鲲之子 · 镇西将军", x: 900, y: 580, px: 344, py: 1210,
      bio: "谢鲲之子，善音乐舞蹈。官镇西将军、豫州刺史，为东晋前期谢氏最显赫者。" },
    { id: "xieyi",    name: "谢奕", zi: "无奕", clan: "陈郡谢氏", years: "？–358",
      title: "谢安之兄 · 谢玄/谢道韫之父", x: 900, y: 650, px: 464, py: 1210,
      bio: "谢裒长子，谢安之兄，官豫州刺史。性嗜酒狂放，其子谢玄、女谢道韫皆为一时之杰。" },
    { id: "xiean",    name: "谢安", zi: "安石", clan: "陈郡谢氏", years: "320–385",
      title: "宰相 · 东山再起", x: 970, y: 650, px: 604, py: 1210, ep: ["EP02 淝水之战", "EP05 谢道韫咏雪", "EP06 许掾不追"],
      bio: "高卧东山，四十余岁始出仕。淝水之战总揽全局，捷报至时“小儿辈大破贼”，下棋如故。本系列核心人物。" },
    { id: "xiewan",   name: "谢万", zi: "万石", clan: "陈郡谢氏", years: "约321–361",
      title: "谢安之弟 · 清谈名士", x: 1040, y: 650, px: 724, py: 1210,
      bio: "谢安之弟，善清谈而疏于军事，北伐败绩，谢氏一度中衰，谢安始出山收拾局面。" },
    { id: "xieshi",   name: "谢石", zi: "石奴", clan: "陈郡谢氏", years: "327–388",
      title: "谢安之弟 · 淝水征讨大都督", x: 1110, y: 650, px: 844, py: 1210, ep: ["EP02 淝水之战"],
      bio: "谢安之弟，淝水之战任征讨大都督，与谢玄同领北府兵，大破前秦。" },
    { id: "xiexuan",  name: "谢玄", zi: "幼度", clan: "陈郡谢氏", years: "343–388",
      title: "谢奕之子 · 北府兵主帅", x: 900, y: 800, px: 464, py: 1320, ep: ["EP02 淝水之战"],
      bio: "谢安之侄、谢奕之子。组建北府兵，淝水之战以少胜多破苻坚百万，奠定谢氏武勋。" },
    { id: "xiedaoyun",name: "谢道韫", zi: "令姜", clan: "陈郡谢氏", years: "约340–？",
      title: "谢奕之女 · 咏絮之才", x: 1040, y: 800, px: 604, py: 1320, ep: ["EP05 谢道韫咏雪"],
      bio: "谢安侄女、谢奕之女，嫁王凝之。“未若柳絮因风起”得“咏絮之才”，为千古才女第一。" },
    { id: "xielingyun", name: "谢灵运", zi: "客儿(小字)", clan: "陈郡谢氏", years: "385–433",
      title: "谢玄之孙 · 山水诗鼻祖", x: 1130, y: 950, px: 464, py: 1430,
      bio: "谢玄之孙，山水诗派鼻祖。尝云“天下才共一石，曹子建独占八斗，我得一斗”。" },

    // ── 名士·隐逸 ───────────────────────────────────────────
    { id: "guanning", name: "管宁", zi: "幼安", clan: "名士·隐逸", years: "158–241",
      title: "割席 · 隐士", x: 1300, y: 220, px: 400, py: 1540, ep: ["EP04 管宁割席"],
      bio: "与华歆同席读书，见门外轩冕过，宁割席分坐曰“子非吾友也”。后避乱辽东，终身不仕。" },
    { id: "huaxin",   name: "华歆", zi: "子鱼", clan: "名士·隐逸", years: "157–232",
      title: "割席 · 后仕曹魏", x: 1375, y: 220, px: 680, py: 1540, ep: ["EP04 管宁割席"],
      bio: "管宁同窗，重名利，被管宁割席绝交。后仕曹魏官至太尉，与王朗并称一时名臣。" },
    { id: "xuqun",    name: "许询", zi: "玄度", clan: "名士·隐逸", years: "生卒不详",
      title: "许掾 · 清谈名士", x: 1300, y: 540, px: 400, py: 1640, ep: ["EP06 许掾不追"],
      bio: "东晋名士，官掾史，故称“许掾”。与谢安、王羲之、支遁交游清谈，是东山名士圈核心。" },
    { id: "zhidun",   name: "支遁", zi: "道林", clan: "名士·隐逸", years: "314–366",
      title: "支公 · 高僧", x: 1375, y: 640, px: 680, py: 1640,
      bio: "东晋高僧，善谈《庄子·逍遥游》，与王羲之、谢安、许询为清谈之友，开士人禅风。" },
    { id: "sunchuo",  name: "孙绰", zi: "兴公", clan: "名士·隐逸", years: "314–371",
      title: "兰亭名士 · 《天台山赋》", x: 1300, y: 740, px: 400, py: 1740,
      bio: "兰亭集会四十一人之一，作《天台山赋》，“掷地有声”即出其口。" },
    { id: "daikui",   name: "戴逵", zi: "安道", clan: "名士·隐逸", years: "331–396",
      title: "画家 · 雕塑家 · 隐士", x: 1375, y: 820, px: 680, py: 1740, ep: ["EP01 雪夜访戴"],
      bio: "东晋画家、雕塑家，隐居剡溪。王子猷雪夜乘舟访之，至门不入而返，曰“乘兴而行，兴尽而返”。" },
  ],

  // relations: from → to, type; bend/pbend = 可选贝塞尔控制点（跨区绕行用）
  relations: [
    // 琅琊王氏（族内）
    { from: "wangxiang", to: "wangyan",   type: "族祖孙" },
    { from: "wangyan",   to: "wangdao",   type: "从兄弟" },
    { from: "wangdun",   to: "wangdao",   type: "从兄弟" },
    { from: "wangdao",   to: "wangkuang", type: "从兄弟" },
    { from: "wangkuang", to: "wangxizhi", type: "父子" },
    { from: "wangxizhi", to: "wangningzhi", type: "父子" },
    { from: "wangxizhi", to: "wanghuizhi",  type: "父子" },
    { from: "wangxizhi", to: "wangxianzhi", type: "父子" },
    { from: "wangdao",   to: "wangxun",   type: "祖孙" },
    // 陈郡谢氏（族内）
    { from: "xiekun",  to: "xiepou",     type: "兄弟" },
    { from: "xiekun",  to: "xieshang",   type: "父子" },
    { from: "xiepou",  to: "xieyi",      type: "父子" },
    { from: "xiepou",  to: "xiean",      type: "父子" },
    { from: "xiepou",  to: "xiewan",     type: "父子" },
    { from: "xiepou",  to: "xieshi",     type: "父子" },
    { from: "xieyi",   to: "xiexuan",    type: "父子" },
    { from: "xieyi",   to: "xiedaoyun",  type: "父女" },
    { from: "xiean",   to: "xiexuan",    type: "叔侄" },
    { from: "xiean",   to: "xiedaoyun",  type: "叔侄女" },
    { from: "xiexuan", to: "xielingyun", type: "祖孙" },
    // 王谢联姻（跨族·双线）
    { from: "wangningzhi", to: "xiedaoyun", type: "夫妻", label: "王谢联姻",
      bend: [540, 1080], pbend: [470, 1160] },
    // 竹林七贤（圈内）
    { from: "ruanji",  to: "ruanxian", type: "叔侄" },
    { from: "jikang",  to: "ruanji",   type: "交游" },
    { from: "jikang",  to: "shantao",  type: "决裂", label: "绝交书" },
    { from: "jikang",  to: "xiangxiu", type: "交游" },
    { from: "ruanji",  to: "liuling",  type: "交游" },
    { from: "ruanji",  to: "wangrong", type: "交游" },
    { from: "shantao", to: "wangrong", type: "交游" },
    // 名士·隐逸（圈内）
    { from: "guanning", to: "huaxin",  type: "决裂", label: "割席" },
    { from: "xuqun",   to: "zhidun",   type: "交游", label: "清谈" },
    { from: "xuqun",   to: "sunchuo",  type: "交游", label: "兰亭" },
    { from: "zhidun",  to: "sunchuo",  type: "交游" },
    // 跨族名士交游（贝塞尔绕行）
    { from: "wangxizhi", to: "xiean",    type: "交游", label: "兰亭",
      bend: [913, 825], pbend: [560, 1050] },
    { from: "xiean",     to: "xuqun",    type: "交游", label: "东山",
      bend: [875, 375] },
    { from: "wanghuizhi", to: "daikui",  type: "交游", label: "雪夜访戴",
      bend: [1010, 720], pbend: [850, 1512] },
    // 竹林 ↔ 王氏（王衍·王戎 从兄弟）
    { from: "wangyan", to: "wangrong", type: "从兄弟", pbend: [870, 470] },
  ],
};
